version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=liveink #  Ensure this matches the service name for PostgreSQL
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=drawing_app
    depends_on:
      db:
        condition: service_healthy #  Wait until PostgreSQL is fully ready

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drawing_app
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck: #  Ensures PostgreSQL is ready before the backend starts
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  pgdata:
